set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

idf_component_register(
    SRCS
        "M00_System/main.cpp"
        "M00_System/Orchestrator.cpp"
        "M00_System/DeviceSettingsValidator.cpp"
        "M00_System/DiagnosticsManager.cpp"
        "M00_System/DiagnosticsTask.cpp"
        "M00_System/I2cTask.cpp"
        "M00_System/LedStripsTask.cpp"
        "M00_System/WatchDog.cpp"
        "M00_System/Queues/DiagnosticsQueueReader.cpp"
        "M00_System/Queues/DiagnosticsQueueWriter.cpp"

        "M10_Composition/Builder/Builder.cpp"
        "M10_Composition/Builder/EspBuilder.cpp"
        "M10_Composition/Context/Context.cpp"
        "M10_Composition/Context/DomainModelsContext.cpp"
        "M10_Composition/Context/DeviceModelsContext.cpp"
        "M10_Composition/Context/DeviceDriversContext.cpp"
        "M10_Composition/Context/ServicesContext.cpp"
        "M10_Composition/Context/TasksContext.cpp"
        "M10_Composition/Context/QueuesContext.cpp"

        "M20_Applications/ApplicationsTask.cpp"
        "M20_Applications/ApplicationsManager.cpp"
        "M20_Applications/Applications/IApplication.cpp"
        "M20_Applications/Applications/Application.cpp"
        "M20_Applications/Applications/Game.cpp"
        "M20_Applications/Applications/Highscore.cpp"
        "M20_Applications/Applications/Highscores.cpp"
        "M20_Applications/Applications/Send.cpp"
        "M20_Applications/Queues/I2cInputQueueReader.cpp"
        "M20_Applications/Queues/I2cOutputQueueWriter.cpp"
        "M20_Applications/Queues/LedStripsQueueWriter.cpp"
        "M20_Applications/Queues/QueueWriters.cpp"
        "M20_Applications/IoStates/IoStates.cpp"
        "M20_Applications/IoStates/JoystickState.cpp"
        "M20_Applications/IoStates/ButtonState.cpp"
        "M20_Applications/IEventListener.cpp"
        "M20_Applications/Applications/Games/Pong.cpp"
        "M20_Applications/Applications/Menu/MenuApplication.cpp"
        "M20_Applications/Applications/Menu/States.cpp"
        "M20_Applications/Applications/Menu/Renderer.cpp"
        "M20_Applications/Applications/Utilities/AutoRun.cpp"
        "M20_Applications/Applications/Utilities/Utility.cpp"

        "M30_Messages/DiagnosticsQueue.cpp"
        "M30_Messages/I2cInputQueue.cpp"
        "M30_Messages/I2cOutputQueue.cpp"
        "M30_Messages/LedStripsQueue.cpp"
        "M30_Messages/Queue.cpp"
        "M30_Messages/QueueProcessor.cpp"
        "M30_Messages/Color.cpp"
        "M30_Messages/Position.cpp"

        "M40_DomainModels/IDomainModel.cpp"
        "M40_DomainModels/DomainModel.cpp"
        "M40_DomainModels/I2c/Displays/Tm1637/Tm1637.cpp"
        "M40_DomainModels/I2c/Displays/Lcd2004/Lcd2004.cpp"
        "M40_DomainModels/I2c/IoPins/IoPins.cpp"
        "M40_DomainModels/I2c/IoPins/Joystick.cpp"
        "M40_DomainModels/I2c/IoPins/Led.cpp"
        "M40_DomainModels/I2c/IoPins/SystemButton.cpp"
        "M40_DomainModels/I2c/I2cOutputQueueReader.cpp"
        "M40_DomainModels/I2c/I2cInputQueueWriter.cpp"
        "M40_DomainModels/LedStrips/LedStrips.cpp"
        "M40_DomainModels/LedStrips/LedStripsQueueReader.cpp"

        "M50_DeviceModels/IDeviceModel.cpp"
        "M50_DeviceModels/DeviceModel.cpp"
        "M50_DeviceModels/Lcd2004/Lcd2004DeviceModel.cpp"
        "M50_DeviceModels/Mcp23017/Mcp23017DeviceModel.cpp"
        "M50_DeviceModels/Tm1637/Tm1637DeviceModel.cpp"
        "M50_DeviceModels/Ws28xx/Ws28xxDeviceModel.cpp"
        "M50_DeviceModels/Ws28xx/GrbBufferFiller.cpp"

        "M60_DeviceDrivers/I2cTaskDeviceDriversDelegate.cpp"
        "M60_DeviceDrivers/IDeviceDriver.cpp"
        "M60_DeviceDrivers/DeviceDriver.cpp"
        "M60_DeviceDrivers/I2c/I2cDeviceDriver.cpp"
        "M60_DeviceDrivers/Lcd2004/Lcd2004DeviceDriver.cpp"
        "M60_DeviceDrivers/Mcp23017/Mcp23017DeviceDriver.cpp"
        "M60_DeviceDrivers/Mcp23017/EspInterruptHandler.cpp"
        "M60_DeviceDrivers/Tm1637/Tm1637DeviceDriver.cpp"
        "M60_DeviceDrivers/LedStripsTaskDeviceDriversDelegate.cpp"
        "M60_DeviceDrivers/Ws28xx/Ws28xxDeviceDriver.cpp"
        "M60_DeviceDrivers/Ws28xx/Ws2812Rmt.cpp"

        "M80_Services/Gpio/Gpio.cpp"
        "M80_Services/Gpio/EspGpio.cpp"
        "M80_Services/I2c/I2c.cpp"
        "M80_Services/I2c/EspI2c.cpp"
        "M80_Services/Nvs/Nvs.cpp"
        "M80_Services/Nvs/EspNvs.cpp"
        "M80_Services/Rmt/Rmt.cpp"
        "M80_Services/Rmt/EspRmt.cpp"
        "M80_Services/Rtos/Rtos.cpp"
        "M80_Services/Rtos/EspRtos.cpp"
        "M80_Services/RtosQueue/RtosQueue.cpp"
        "M80_Services/RtosQueue/EspRtosQueue.cpp"
        "M80_Services/RtosTask/RtosTask.cpp"
        "M80_Services/RtosTask/EspRtosTask.cpp"
        "M80_Services/Random/Random.cpp"
        "M80_Services/Random/EspRandom.cpp"
        "M80_Services/Uart/Uart.cpp"
        "M80_Services/Uart/EspUart.cpp"

        "M90_Utilities/Assert/Assert.cpp"
        "M90_Utilities/Dirty/Dirty.cpp"
        "M90_Utilities/Dirty/IDirty.cpp"
        "M90_Utilities/Initializable/Initializable.cpp"
        "M90_Utilities/Initializable/IInitializable.cpp"
        "M90_Utilities/Log/Log.cpp"
        "M90_Utilities/Math/BitUtilities.hpp"
        "M90_Utilities/Math/MathUtilities.cpp"
        "M90_Utilities/String/StringUtilities.cpp"
        "M90_Utilities/Task/Task.cpp"
        "M90_Utilities/Time/TimeUtilities.cpp"

    INCLUDE_DIRS "."

    REQUIRES
        driver
)
