set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

idf_component_register(
    SRCS
        "L0_System/main.cpp"
        "L0_System/Orchestrator.cpp"
        "L0_System/DeviceSettings.cpp"
        "L0_System/DeviceSettingsValidator.cpp"
        "L0_System/I2cTask.cpp"
        "L0_System/LedStripsTask.cpp"

        "L1_Composition/Builder/Builder.cpp"
        "L1_Composition/Builder/EspBuilder.cpp"
        "L1_Composition/Context/Context.cpp"
        "L1_Composition/Context/DomainModelsContext.cpp"
        "L1_Composition/Context/DeviceModelsContext.cpp"
        "L1_Composition/Context/DeviceDriversContext.cpp"
        "L1_Composition/Context/ServicesContext.cpp"
        "L1_Composition/Context/TasksContext.cpp"
        "L1_Composition/Context/QueuesContext.cpp"

        "L2_Applications/ApplicationsTask.cpp"
        "L2_Applications/ApplicationsManager.cpp"
        "L2_Applications/Applications/Demos/AutoRun/AutoRun.cpp"
        "L2_Applications/Applications/Application.cpp"
        "L2_Applications/Applications/Send.cpp"
        "L2_Applications/Queues/Queue.cpp"
        "L2_Applications/Queues/I2cInputQueueReader.cpp"
        "L2_Applications/Queues/I2cOutputQueueWriter.cpp"
        "L2_Applications/Queues/LedStripsQueueWriter.cpp"
        "L2_Applications/Queues/QueueWriters.cpp"
        "L2_Applications/IoStates/IoStates.cpp"
        "L2_Applications/IoStates/JoystickState.cpp"
        "L2_Applications/IoStates/ButtonState.cpp"

        "L2_Applications/Applications/Menu/MenuApplication.cpp"
        "L2_Applications/Applications/Menu/States.cpp"
        "L2_Applications/Applications/Menu/Renderer.cpp"
        "L2_Applications/Applications/Demos/AutoRun/AutoRun.cpp"

        "L3_Messages/LedStripsQueue.cpp"
        "L3_Messages/I2cInputQueue.cpp"
        "L3_Messages/I2cOutputQueue.cpp"
        "L3_Messages/Color.cpp"
        "L3_Messages/Position.cpp"

        "L4_DomainModels/DomainModel.cpp"
        "L4_DomainModels/I2c/Displays/Displays.cpp"
        "L4_DomainModels/I2c/Displays/Tm1637/Tm1637.cpp"
        "L4_DomainModels/I2c/Displays/Lcd2004/Lcd2004.cpp"
        "L4_DomainModels/I2c/IoPins/IoPins.cpp"
        "L4_DomainModels/I2c/IoPins/Joystick.cpp"
        "L4_DomainModels/I2c/IoPins/Led.cpp"
        "L4_DomainModels/I2c/IoPins/SystemButton.cpp"
        "L4_DomainModels/I2c/I2cOutputQueueReader.cpp"
        "L4_DomainModels/I2c/I2cInputQueueWriter.cpp"
        "L4_DomainModels/LedStrips/LedStrips.cpp"
        "L4_DomainModels/LedStrips/LedStripsQueueReader.cpp"

        "L5_DeviceModels/DeviceModel.cpp"
        "L5_DeviceModels/Lcd2004/Lcd2004DeviceModel.cpp"
        "L5_DeviceModels/Mcp23017/Mcp23017DeviceModel.cpp"
        "L5_DeviceModels/Tm1637/Tm1637DeviceModel.cpp"
        "L5_DeviceModels/Ws28xx/Ws28xxDeviceModel.cpp"

        "L6_DeviceDrivers/I2cTaskDeviceDriversDelegate.cpp"
        "L6_DeviceDrivers/DeviceDriver.cpp"
        "L6_DeviceDrivers/I2c/I2cDeviceDriver.cpp"
        "L6_DeviceDrivers/I2c/EspI2cDeviceDriver.cpp"
        "L6_DeviceDrivers/Lcd2004/Lcd2004DeviceDriver.cpp"
        "L6_DeviceDrivers/Lcd2004/EspLcd2004DeviceDriver.cpp"
        "L6_DeviceDrivers/Mcp23017/Mcp23017DeviceDriver.cpp"
        "L6_DeviceDrivers/Mcp23017/EspMcp23017DeviceDriver.cpp"
        "L6_DeviceDrivers/Tm1637/Tm1637DeviceDriver.cpp"
        "L6_DeviceDrivers/Tm1637/EspTm1637DeviceDriver.cpp"
        "L6_DeviceDrivers/LedStripsTaskDeviceDriversDelegate.cpp"
        "L6_DeviceDrivers/Ws28xx/Ws28xxDeviceDriver.cpp"
        "L6_DeviceDrivers/Ws28xx/EspWs28xxDeviceDriver.cpp"
        "L6_DeviceDrivers/Ws28xx/Ws2812Rmt.cpp"

        "L8_Services/Rtos/Rtos.cpp"
        "L8_Services/Rtos/EspRtos.cpp"
        "L8_Services/RtosQueue/RtosQueue.cpp"
        "L8_Services/RtosQueue/EspRtosQueue.cpp"
        "L8_Services/RtosTask/RtosTask.cpp"
        "L8_Services/RtosTask/EspRtosTask.cpp"
        "L8_Services/Random/Random.cpp"
        "L8_Services/Random/EspRandom.cpp"

        "L9_Utilities/Assert/Assert.cpp"
        "L9_Utilities/Debug/Debug.cpp"
        "L9_Utilities/Dirty/Dirty.cpp"
        "L9_Utilities/Dirty/IDirty.cpp"
        "L9_Utilities/Math/MathUtilities.cpp"
        "L9_Utilities/String/StringUtilities.cpp"
        "L9_Utilities/Task/Task.cpp"
        "L9_Utilities/Time/TimeUtilities.cpp"

    INCLUDE_DIRS "."

    REQUIRES
        driver
)