@startuml#ffff00

top to bottom direction
skinparam ranksep 120
skinparam nodesep 20
skinparam packageStyle rectangle

package "SystemTask" as SystemTask {
    class SytemAppsControlQueue {}
    class SystemIoQueue {}
    class SystemFileQueue {}
}

package "AppsTask" as AppsTask {
    class AppsControlQueue {}
    class AppsIoQueue {}
    class AppsAudioQueue {}
}

package "I2cTask" as I2cTask #yellow { 
    class I2cQueue #yellow {}
}

package "LedStripTask" as LedStripTask  #yellow {
    class LedStripQueue #yellow {}
}  

package "AudioTask" as AudioTask {
    class AudioQueue {}
}

package "SpiTask" as SpiTask {
    class FileQueue {}

    class LogQueue {}
}

SystemTask -[hidden]down--> AppsTask
AppsTask -[hidden]down-> I2cTask
I2cTask -[hidden]down-> LedStripTask
LedStripTask -[hidden]down-> AudioTask
AudioTask -[hidden]down-> SpiTask

SystemTask .down.> AppsControlQueue : StartApp(appId), \n StopApp(appId)
AppsTask .up.> SytemAppsControlQueue : AppStopped
SystemTask .down.> I2cQueue : <b>I2c_Initialize</b>, \n Led, \n Tm1637_Time, \n Tm1637_Value, \n <b>Lcd1602Display_Initialize</b>, \n <b>Lcd1602Display_TextLines</b>, \n Lcd1602Display_Cursor
AppsTask .down.> I2cQueue : Led, \n Tm1637_Time, \n Tm1637_Value, \n Lcd1602Display_TextLines, \n Lcd1602Display_Cursor
I2cTask .up.> SystemIoQueue : JoystickButtonUp/Down\Held, \n Joystick, \nSystemButtonUp/Down/Held
SystemTask .down.> AppsIoQueue : Joystick...
AppsTask --> LedStripQueue : <b>LedStrip_Initialize</b>, \n <b>LedStrip_BufferReady</b>
SystemTask .down.> AudioQueue : LoadWav, \n StreamWav
AppsTask .down.> AudioQueue : PlayWav, \n StopWav, \n SetVolume, \n StartMic, \n StopMic
AudioTask .up.> AppsAudioQueue : MicBufferReady
AudioTask .down.> FileQueue : LoadFile, \n OpenFile, \n CloseFile
SpiTask .up.> AudioTask : StreamBufferReady
SystemTask .down.> FileQueue : LoadFile, \n SaveFile
SpiTask .up.> SystemFileQueue : FileReady
AnyTask .down.> LogQueue : LogValue, \n LogText

@enduml
