@startuml
top to bottom direction

title LAYERS OF FRAXIS

skinparam packageStyle rectangle
skinparam lineThickness 2

package "L0 System Layer" as SystemLayer #cyan
{
    class main {}
    class WindowsSimulator {}
    class Orchestrator {}
}

package "L1 Composition Layer" as CompositionLayer #red 
{
    class Builder {}
    class EspBuilder {}
    class WindowsBuilder {}
    class Context {}

    EspBuilder -|> Builder
    WindowsBuilder -|> Builder
}

main --> EspBuilder
WindowsSimulator --> WindowsBuilder

Orchestrator *-- Builder
Orchestrator *-- Context

package "L2 Applications Layer" as ApplicationsLayer #gold
{
    class ApplicationsTask #gold {}
}

SystemLayer -d[hidden]-- CompositionLayer 
CompositionLayer -d[hidden]-- ApplicationsLayer

main *-->ApplicationsTask

package "L3 Messages (Layer)" as MessagesLayer #White
{
    class LedStripsQueue <<queue>> 
    {
        + Pixel(uint8_t horizontal, uint8_t vertical, RGB color)
        + Row(uint8_t row, RGB color)
        + Column(uint8_t column, RGB color)
        + Orientation(EOrientation orientation)
        + SyncToDriver()
    }

    class OutputQueue <<queue>> 
    {
        Led(ELedId led_id, bool on)
        Mcp23017Interrupt()
    }

    class InputQueue <<queue>> 
    {
        JoystickDirection(EJoystickId joystickId, 
            EJoystickDirection joystickDirection)
        JoystickButton(EJoystickId joystickBId, bool pressed)
        Button(EButtonId id, bool pressed)
    }
}

package "L4 Domain Models Layer" as DomainModelsLayer #LightSkyBlue
{
    class I2cTask <<I2cTask>> #yellow
    class IoPins <<I2cTask>> #yellow
    class Lcd2004 <<I2cTask>> #yellow
    class Tm1637 <<I2cTask>> #yellow
    class LedStripsTask <<LedStripTask>> #cyan
    class LedStrips <<LedStripTask>> #cyan
}

Orchestrator --> I2cTask: Initialize/\nStart
Orchestrator --> LedStripsTask: Initialize/\nStart

ApplicationsTask --> LedStripsQueue
ApplicationsTask --> OutputQueue
InputQueue       --> ApplicationsTask
InputQueue -d[hidden]- DomainModelsLayer

OutputQueue     --> I2cTask
LedStripsQueue  --> LedStripsTask
I2cTask         --> InputQueue

package "L5 Device Models Layer" as DeviceModelsLayer #SteelBlue
{
    class Ws28xxModel <<LedStripTask>> #cyan
    class Mcp23017Model <<I2cTask>> #yellow
    class Tm1637Model <<I2cTask>> #yellow
    class Lcd2004Model <<I2cTask>> #yellow

    LedStrips *-- Ws28xxModel
    IoPins *- Mcp23017Model
    Tm1637 *- Tm1637Model
    Lcd2004 *- Lcd2004Model
}

DeviceModelsLayer -u[hidden]-- DomainModelsLayer

package "L6 Device Drivers Layer" as DeviceDriversLayer #4f8
{
    class WindowsWs28xxDriver <<LedStripTask>> #cyan
    class Ws28xxDriver <<LedStripTask>> #cyan
    WindowsWs28xxDriver -|> Ws28xxDriver 
    class Mcp23017Driver <<I2cTask>> #yellow
    class Tm1637Driver <<I2cTask>> #yellow
    class Lcd2004Driver <<I2cTask>> #yellow
}

Ws28xxModel    *-- Ws28xxDriver 
Mcp23017Model  *-- Mcp23017Driver 
Mcp23017Driver  -u-> OutputQueue : Mcp23017Interrupt
Tm1637Model    *-- Tm1637Driver
Lcd2004Model   *-- Lcd2004Driver

package "L7 Windows GDI Layer" as WindowsGdiLayer #pink
{
    class GdiLedStrips
    class GdiJoystick
    class GdiLed
    class GdiButton
    class GdiTm1637
    class GdiLcd2004
}

DeviceDriversLayer -u[hidden]-- WindowsGdiLayer

WindowsWs28xxDriver ->  GdiLedStrips : Update
Mcp23017Driver --> GdiJoystick : Update
Mcp23017Driver -> GdiLed
Tm1637Driver --> GdiTm1637
Lcd2004Driver --> GdiLcd2004

package "L8 Services Layer" as ServicesLayer #grey
{
    class Intellisense {}
    class Gpio {}
    class I2c {}
    class Rmt {}
    class Rtos {}
    class RtosQueue {}
    class RtosTask {}
    class Intellisense {}
    class Random {}
}
note top of ServicesLayer
    Can be used by any layer
end note

ServicesLayer -l[hidden]- WindowsGdiLayer

' CompositionLayer --> ServicesLayer
' ApplicationsLayer --> ServicesLayer
' DomainModelsLayer --> ServicesLayer
' DeviceModelsLayer --> ServicesLayer
' DeviceDriversLayer --> ServicesLayer
' WindowsGdiLayer --> ServicesLayer

package "L9 Utilities Layers" as UtilitiesLayer #Beige
{
    class Algorithm {}
    class Array {}
    class Assert {}
    class Debug {}
    class Dirty {}
    class Initializable {}
    class Log {}
    class MathUtilities {}
    class StringUtilities {}
    class Task {}
    class TimeUtilities {}
}
note top of UtilitiesLayer
    Can be used by any layer
end note

UtilitiesLayer -l[hidden]- WindowsGdiLayer

' CompositionLayer --> UtilsLayer
' ApplicationsLayer --> UtilsLayer
' DomainModelsLayer --> UtilsLayer
' DeviceModelsLayer --> UtilsLayer
' DeviceDriversLayer --> UtilsLayer
' WindowsGdiLayer --> UtilsLayer
' ServicesLayer --> UtilsLayer

'WindowsGdiLayer -u[hidden]-- ServicesLayer

@enduml
