@startuml
top to bottom direction

title L0 SYSTEM TASK

skinparam packageStyle rectangle
skinparam lineThickness 2

class main 
{
}

class WindowsSimulator 
{
}

class Orchestrator 
{
    + Orchestrator(Builder& builder)
    + Run()
    + ValidateDeviceSettings()
    - CreateLinks()
    - LinkDeviceModelsToDeviceDrivers()
    - InitializeDeviceModels()
    - InitializeDevicesDrivers()
    - InitializeTasks()
    - StartTasks()
}

main *-- Orchestrator
main *-- Context
WindowsSimulator *-- Orchestrator
WindowsSimulator *-- Context 

class DeviceSettingsValidator
{
    + <<static>> Validate()
    - <<static>> ValidatePins()
    - <<static>> ValidateI2c()
    - <<static>> ValidateMcp23017()
}

DeviceSettingsValidator o-- DeviceSettings
Orchestrator *-- DeviceSettingsValidator

class Builder <<L1 Compositions Layer>> {}
class EspBuilder  <<L1 Compositions Layer>> {}
class WindowsBuilder  <<L1 Compositions Layer>> {}
class Context <<L1 Compositions Layer>> {}

EspBuilder -|> Builder
WindowsBuilder -|> Builder

main --> EspBuilder
WindowsSimulator --> WindowsBuilder

Orchestrator o-- Builder
Orchestrator o-- Context

class RtosTask <<L8 Service Layer>>
{
    + <<abstract>> Start()
    + <<abstract>> DelayTask(uint32_t ms)
    + <<abstract>> GetTaskTickCount()
    + <<abstract>> CreateQueue(
        uint32_t queueLength, \n uint32_t itemSize): RtosQueue*
}
ApplicationsTask -u-|> Task

class Task
{   
    + SetRtosTask(RtosTask& rtosTask)
    + GetRtosTask(): RtosTask& 
    + <<abstract>> Initialize()
    + <<abstract>> Run()
}

Task *-- RtosTask

Orchestrator *-- ApplicationsTask 

class I2cTask <<I2cTask, L0 Systems Layer>> #yellow
{
    + I2cTask(Context& context)
    + Initialize()
    + Run()
    + <<static>> TaskEntry(void* param);
}

I2cTask -u-|> Task
I2cTask o-- Context

class IoPins <<L4 Domain Models>> {}
I2cTask o-- IoPins 
class Displays <<L4 Domain Models>> {}
I2cTask o-- Displays 
class OutputQueue <<L3 Messages>> {}
I2cTask o-- OutputQueue 
class OutputQueueReader <<L4 Domain Models>> {}
I2cTask o-- OutputQueueReader 
class I2cTaskDeviceDriversDelegate <<L6 Device Drivers>> {}
I2cTask o-- I2cTaskDeviceDriversDelegate 

Orchestrator *-- I2cTask

class DiagnosticsTask <<L0 Systems Layer>> #grey
{
    + DiagnosticsTask(Context& context)
    + ~DiagnosticsTask()
    + Initialize()
    + Run()
    + <<static>> TaskEntry(void* param);
}

class Context <<L1 Compositions Layer>> {}

DiagnosticsTask -u-|> Task
DiagnosticsTask o-- Context

class QueueProcessor <<L3 Messages>>
{
}

class DiagnosticsQueueReader #grey
{
    + DiagnosticsQueueReader(
        DiagnosticsQueue& diagnosticsQueue, \n WatchDog& watchDog, \n DiagnosticsManager& diagnosticsManager)
    + ~DiagnosticsQueueReader()
    + bool HandleMessage()
    - DiagnosticsQueue& GetDiagnosticsQueue()
}

DiagnosticsQueueReader o-- WatchDog
DiagnosticsQueueReader o-- DiagnosticsManager

QueueProcessor <|-- DiagnosticsQueueReader

class DiagnosticsQueueWriter #grey
{
    + DiagnosticsQueueWriter(
        DiagnosticsQueue& diagnosticsQueue)
    + ~DiagnosticsQueueWriter()
    + void SendHeartBeat(
        Types::ETaskId taskId, \n uint64_t timeStamp)
    + void SendTaskData(
        Types::ETaskId taskId, \n uint64_t timeStamp, \n uint64_t stackSize)
    + void SendLogEntry(
        Types::ETaskId taskId, \n uint64_t timeStamp, \n Types::ELogLevel logLevel, \n const char* text)
    - DiagnosticsQueue& GetDiagnosticsQueue()
}

QueueProcessor <|-- DiagnosticsQueueWriter

class DiagnosticsManager #grey
{
    + DiagnosticsManager(Context& context)
    + ~DiagnosticsManager()
    + void OnTaskData(
        Types::ETaskId taskId, \n uint64_t timeStamp, \n uint64_t stackSize)
    + void OnLogEntry(
        Types::ETaskId taskId, \n uint64_t timeStamp, \n Types::ELogLevel logLevel, \n const char* text)
}

DiagnosticsManager o-- Context

class WatchDog #grey
{
    + <<static>> const uint16_t APPLICATIONS_TASK_HEARTBEAT_TIMEOUT_MS
    + <<static>> const uint16_t I2C_TASK_HEARTBEAT_TIMEOUT_MS
    + <<static>> const uint16_t LED_STRIPS_TASK_HEARTBEAT_TIMEOUT_MS
    + Watchdog(DiagnostDiagnosticsManager& diagnosticsManager);
    + ~WatchDog()
    + void OnHeartBeat(Types::ETaskId taskId, uint64_t timeStamp)
    + void CheckTimeouts()
    - uint64_t _lastApplicationsTaskHeartBeatTimeStamp
    - uint64_t _lastI2cTaskHeartBeatTimeStamp
    - uint64_t _lastLedStripsTaskHeartBeatTimeStamp
}

WatchDog o-- DiagnosticsManager

class DiagnosticsQueue <<L3 Messages>>
{
}

DiagnosticsTask o-- DiagnosticsQueue
DiagnosticsTask *-- DiagnosticsQueueReader
DiagnosticsTask *-- DiagnosticsManager
DiagnosticsTask *-- WatchDog

class ApplicationsTask <<L2 Applications Layer>> #gold
{
}

class LedStripsTask <<LedStripsTask, L0 Systems Layer>> #lightblue
{
    + LedStripsTask(Context& context)
    + Initialize()
    + Run()
    + <<static>> void TaskEntry(void* param);    
}

LedStripsTask -u-|> Task
LedStripsTask o-- Context
Orchestrator *-- LedStripsTask

class DeviceSettings
{
    + <<static>> const uint32_t UART_BAUD_RATE
    + <<static>> const uint16_t UART_RX_BUFFER_SIZE
    + <<static>> const uint16_t UART_TX_BUFFER_SIZE
    + <<static>> const uint8_t PIN_I2C_SCL
    + <<static>> const uint8_t PIN_I2C_SDA
    + <<static>> const uint8_t PIN_MCP23017_INTERRUPT
    + <<static>> const uint8_t PIN_LED_STRIP_DATA
    + <<static>> const uint8_t PIN_TM1637_CLOCK;
    + <<static>> uint8_t       PIN_TM1637_CENTRAL_PANEL_DATA;
    + <<static>> uint8_t       PIN_TM1637_PLAYER_1_DATA;
    + <<static>> uint8_t       PIN_TM1637_PLAYER_2_DATA;

    + <<static>> const uint8_t I2C_PORT
    + <<static>> const uint32_t I2C_FREQUENCY
    + <<static>> const uint8_t I2C_ADDRESS_MCP_23017
    + <<static>> const uint8_t I2C_ADDRESS_LCD_2004

    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_1_JOYSTICK_UP;
    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_1_JOYSTICK_DOWN;
    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_1_JOYSTICK_LEFT;
    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_1_JOYSTICK_RIGHT;
    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_1_JOYSTICK_BUTTON;
    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_1_LED;

    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_2_JOYSTICK_UP;
    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_2_JOYSTICK_DOWN;
    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_2_JOYSTICK_LEFT;
    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_2_JOYSTICK_RIGHT;
    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_2_JOYSTICK_BUTTON;
    + <<static>> const uint8_t  MCP23017_BIT_PLAYER_2_LED;

    + <<static>> const uint8_t  MCP23017_BIT_SYSTEM_BUTTON;
    + <<static>> const uint8_t  MCP23017_BIT_PAUSE_LED;
    + <<static>> const uint8_t  MCP23017_BIT_SELECT_LED;
    + <<static>> const uint8_t  MCP23017_BIT_SETUP_LED;
}

Orchestrator *-- DeviceSettings

@enduml
