@startuml

title 1 COMPOSITION LAYER

skinparam packageStyle rectangle
skinparam lineThickness 2

class main <<ESP>>
{
    main()
}

package "Components Builder" as ComponentsBuilder_Package
{
    class ComponentsBuilder
    {
        + Build(Context& context)
        # GetContext() : Context&
        # <<abstract>> BuildDeviceDriversContext()
        # <<abstract>> BuildServicesContext() 
        - BuildDomainModelsContext()
        - BuildDeviceModelsContext()
        - BuildTasks()
        - BuildQueues()
        - CreateLinks()
    }

    class EspComponentsBuilder
    {
        # BuildDeviceDriversContext()
        # BuildServicesContext() 
    }
    EspComponentsBuilder -u-|> ComponentsBuilder

    class WindowsComponentsBuilder
    {
        # BuildDeviceDriversContext(Context& context)
        # BuildServicesContext(Context& context) 
    }
    WindowsComponentsBuilder -u-|> ComponentsBuilder

    main *-- EspComponentsBuilder
}

package "Context" as ContextPackage
{
    class Context 
    {
        + DomainModelsContext& GetDomainModels()
        + DeviceModelsContext& GetDeviceModels()
        + DeviceDriversContext& GetDeviceDrivers() 
        + ServicesContext& GetServices() 
        + TasksContext& GetTasks()
        + QueuesContext& GetQueues()
    }

    class DomainModelsContext
    {
        + Set(LedStrips ledStrips, IoPins ioPins, \n Displays displays)
        + GetLedStrips() : LedStrips& 
        + GetIoPins() : IoPins& 
        + GetDisplays() : Displays& 

        - LedStrips _ledStrips
        - IoPins _ioPins
        - Lcd2004 _lcd2004
        - Tm1637 _tm1637CentralPanel
        - Tm1637 _tm1637Player1
        - Tm1637 _tm1637Player2
    }

    class DeviceModelsContext
    {
        + Set(Ws28xxModel ws28xxModel, \n I2cModel i2cModel, \n Mcp23017Model mcp23017Model, \n Lcd2004Model lcd2004Model, \n Tm1637Model tm1637ModelCentralPanel, \n Tm1637Model tm1637ModelPlayer1, \n Tm1637Model tm1637ModelPlayer2);
        + GetLedStripModel() : Ws28xxModel& 
        + GetMcp23017Model() : Mcp23017Model& 
        + GetLcd2004Model() : Lcd2004Model& 
        + GetTm1637ModelCentralPanel() : Tm1637Model& 
        + GetTm1637ModelPlayer1() : Tm1637Model& 
        + GetTm1637ModelPlayer2() : Tm1637Model& 
        - I2cModel _i2cModel
        - Ws28xxModel _ws28xxModel
        - Mcp23017Model _mcp23017Model
        - Lcd2004Model _lcd2004Model
        - Tm1637Model _tm1637ModelCentralPanel
        - Tm1637Model _tm1637ModelPlayer1
        - Tm1637Model _tm1637ModelPlayer2
    }
    
    class DeviceDriversContext
    {

        + Set(Ws28xxDriver> ws28xxDriver, I2cDriver i2cDriver, \n Mcp23017Driver mcpDriver, \n Lcd2004Driver lcd2004Driver, \n Tm1637Driver tm1637DriverCentralPanel, \n Tm1637Driver tm1637DriverPlayer1, \n Tm1637Driver tm1637DriverPlayer2);

        + GetWs28xxDriver() : Ws28xxDriver& 
        + GetI2cDriver() : I2cDriver& 
        + GetMcp23017Driver() : Mcp23017Driver& 
        + GetLcd2004Driver() : Lcd2004Driver& 
        + GetTm1637CentralPanel() : Tm1637Driver& 
        + GetTm1637Player1() : Tm1637Driver& 
        + GetTm1637Player2() : Tm1637Driver& 

        - Ws28xxDriver _ws28xxDriver
        - I2cDriver _i2cDriver
        - Mcp23017Driver _mcp23017Driver
        - Lcd2004Driver _lcd2004Driver
        - Tm1637Driver _tm1637DriverCentralPanel
        - Tm1637Driver _tm1637DriverPlayer1
        - Tm1637Driver _tm1637DriverPlayer2
    }

    class ServicesContext
    {
        + Set(Rtos rtos, RtosQueue queue, Random random)
        + GetRtos() : Rtos& 
        + GetQueue() : RtosQueue& 
        + GetRandom() : Random& 
        - _rtos : Rtos 
        - _queue : RtosQueue 
        - _random : Random 
    }

    class RtosTasksContext
    {
        + Set(RtosTask applicationsTask, RtosTask i2cTask, RtosTask ledStripsTask)
        + InitializeAll();
        + StartAll()
        + GetApplicationsTask() : RtosTask& 
        + GetI2cTask() : RtosTask& 
        + GetLedStripsTask(): RtosTask& 
        - RtosTask _applicationsTask
        - RtosTask _i2cTask
        - RtosTask _ledStripsTask
    }

    class RtosQueuesContext
    {
        + Set(RtosQueue ledStripsQueue, RtosQueue inputQueue, RtosQueue outputQueue)
        + GetLedStripsQueue(): RtosQueue& 
        + GetInputQueue(): RtosQueue& 
        + GetOutputQueue() : RtosQueue& 
        - RtosQueue _ledStripsQueue;
        - RtosQueue _inputQueue;
        - RtosQueue _outputQueue;
    }

    Context *-- DomainModelsContext
    Context *-- DeviceModelsContext
    Context *--- DeviceDriversContext
    Context *--- ServicesContext
    Context *---- RtosTasksContext
    Context *---- RtosQueuesContext
}

main *- Context
ComponentsBuilder o-- Context
EspComponentsBuilder ..-> Context : fills
WindowsComponentsBuilder ..-> Context : fills

@enduml
