@startuml

title 2 APPLICATIONS LAYER

skinparam packageStyle rectangle
skinparam lineThickness 2

class ApplicationsTask  
{
    - Context _context
    + Initialize()
    + Run()
    + static void TaskEntry(void* param)
    - _ledStripsQueue : LedStripsQueue
    - _inputQueue : InputQueue
    - _outputQueue : OutputQueue
}

class RtosTask <<L8_SERVICE_LAYER>>
{
    + <<abstract>> Start()
    + <<abstract>> DelayTask(uint32_t ms)
    + <<abstract>> GetTaskTickCount()
    + <<abstract>> CreateQueue(\n uint32_t queueLength, uint32_t itemSize): RtosQueue*
}

class Task <<Service>>
{   
    + SetRtosTask(RtosTask& rtosTask)
    + GetRtosTask(): RtosTask& 
    + <<abstract>> Initialize()
    + <<abstract>> Run()
}

Task *- RtosTask

ApplicationsTask -u-|> Task

interface IEventListener
{
    + <<abstract>> OnJoystickDirectionChanged(\n IoStates::EJoystickId id, JoystickState::EDirection direction)
    + <<abstract>> OnJoystickButtonChanged(\n IoState:EJoystickId id, bool state)
    + <<abstract>> OnSystemButtonChanged(bool state)
}

class ApplicationsManager
{
    + GetApplicationsTask(): ApplicationsTask
    + GetIoStates(): IoStates
    + OnJoystickDirectionChanged(\n IoStates::EJoystickId id, JoystickState::EDirection direction)
    + OnJoystickButtonChanged(\n IoState:EJoystickId id, bool state)
    + OnSystemButtonChanged(bool state)
}

ApplicationsManager -u-|> IEventListener

package "I/O States"
{
    class JoystickState 
    {
        + EJoystickDirection { \n Centered, Up, UpRight, Right, DownRight, \n Down, DownLeft, Left, UpLeft }
        - direction : EJoystickDirection
        - buttonState : bool
        + GetDirection() : EJoystickDirection
        + SetDirection(EJoystickDirection joystickDirection)
        + GetButtonState() : bool
        + SetButtonState(bool state)
    }
    
    class ButtonState 
    {
        - state : bool
        + GetState() : bool
        + SetState(bool state)
    }
    
    class IoStates
    {
        + EJoystickId : { Player1, Player2 }
        + GetJoystickState(EJoystickId): JoystickState
        + GetSystemButtonState(): ButtonState
    }

    IoStates *--"2" JoystickState
    IoStates *-- ButtonState
}

package "Applications" 
{
    interface IApplication 
    {
        + {abstract} Start()
        + {abstract} Pause()
        + {abstract} Resume()
        + {abstract} Stop()
    }

    abstract class Application <<abstract>>
    {
        + EId { Menu, Pong }  
        + EType { Menu, Game, Demo, Tool, Utility }
        + GetApplicationsManager() : ApplicationsManager
        + GetId() : EId
        + GetType() : EType
        + GetName() : string
        + GetContext() : Context&
        - _id : EId
        - _type : EType
        - _name : string
        - _context : Context
    }

    Application -u-|> IApplication
    Application -u-|> IEventListener

    package "Menu Application" as MenuApplicationPackage
    {
        class MenuApplication 
        {
            + Start()
            + Pause()
            + Resume()
            + Stop()
                
            + OnJoystickDirectionChanged(\n IoStates::EJoystickId id, JoystickState::EDirection direction)
            + OnJoystickButtonChanged(\n IoState:EJoystickId id, bool state)
            + OnSystemButtonChanged(bool state)
        }

        class InputProcessor 
        {
            + GetMenuApplication() : MenuApplication
        }

        class States
        {

        }

        class Renderer 
        {
            + GetMenuApplication() : MenuApplication
            + Render(): RenderOutput
        }

        class RenderOutput
        {
            + GetMenuApplication() : MenuApplication
        }

        Renderer *- RenderOutput
        
        MenuApplication *-- InputProcessor
        MenuApplication *-- States
        MenuApplication *--- Renderer
        MenuApplication *--- RenderOutput
    }        

    class PongApplication 
    {
        + Start(Application::EId)
        + Pause(Application::EId)
        + Resume(Application::EId)
        + Stop(Application::EId)
        + OnJoystickDirectionChanged(\n IoStates::EJoystickId id, JoystickState::EDirection direction)
        + OnJoystickButtonChanged(\n IoState:EJoystickId id, bool state)
        + OnSystemButtonChanged(bool state)

    }

    PongApplication -u-|> Application
}

MenuApplication -u--|> Application

ApplicationsTask *-- ApplicationsManager
ApplicationsManager *-- Application
note on link
    Menu is always 
    application [0]
end note

ApplicationsManager *-- MenuApplication
ApplicationsManager *-- IoStates

@enduml
