@startuml

title 2 APPLICATIONS LAYER

skinparam packageStyle rectangle
skinparam lineThickness 2

class ApplicationsTask  
{
    - Context _context
    + Initialize()
    + Run()
    + static void TaskEntry(void* param)
}

class RtosTask <<L8_SERVICE_LAYER>>
{
    + <<abstract>> Start()
    + <<abstract>> DelayTask(uint32_t) ms)
    + <<abstract>> GetTaskTickCount()
    + <<abstract>> CreateQueue(uint32_t queueLength, uint32_t itemSize): RtosQueue*
}

class Task <<Service>>
{   
    + SetRtosTask(RtosTask& rtosTask)
    + GetRtosTask(): RtosTask& 
    + <<abstract>> Initialize()
    + <<abstract>> Run()
}

Task -u-|> RtosTask

ApplicationsTask -u-|> Task

class ApplicationsManager
{
    GetApplicationsTask(): ApplicationsTask
    GetIoStateManager(): IoStateManager
}

package "I/O States"
{
    class JoystickState 
    {
        - direction : EJoystickDirection
        - buttonState : bool
        + GetDirection() : EJoystickDirection
        + GetButtonState() : bool
    }
    
    class ButtonState 
    {
        - buttonState : bool
        + GetState() : bool
    }
    
    interface IoStateManager
    {
        + EJoystickId : { PLAYER_1, PLAYER_2 }
        + EButtonId : { SYSTEM }
        + GetJoystick(EJoystickId): EJoystickId
        + GetButton(EButtonId): EButtonId
    }

    IoStateManager *--"2" JoystickState : (Player 1, \n Player2)
    IoStateManager *-- ButtonState : (System Button)
}

package "Applications" 
{
    interface IApplication 
    {
        + {abstract} Start(EApplicationId)
        + {abstract} Pause(EapplicationId)
        + {abstract} Resume(EApplicationId)
        + {abstract} Stop(EApplicationId)
    }

    abstract class Application <<abstract>>
    {
        + GetApplicationsManager() : ApplicationsManager
        + EApplicationId { PONG, ... }
    }

    Application -u-|> IApplication

    class GameApplication <<abstract>> 
    {
    }

    class DemoApplication <<abstract>> 
    {
    }

    class ToolApplication <<abstract>>
    {
    }

    class UtilityApplication <<abstract>>
    {
    }

    GameApplication     -u-|> Application
    DemoApplication     -u-|> Application 
    ToolApplication     -u-|> Application
    UtilityApplication  -u-|> Application

    class Pong  {}
    Pong -u-|> GameApplication

    package "Menu Application" as MenuApplicationPackage
    {
        class MenuApplication 
        {
        }

        class MenuRenderer 
        {
            + GetMenuApplication() : MenuApplication
            + Render(): RenderOutput
        }

        class RenderOutput
        {
            + GetMenuApplication() : MenuApplication
        }

        MenuRenderer *- RenderOutput
        
        class MenuInputProcessor 
        {
            + GetMenuApplication() : MenuApplication
        }

        MenuApplication *-- MenuRenderer
        MenuApplication *-- RenderOutput
        MenuApplication *-- MenuInputProcessor
    }        
}

MenuApplication     -u---|> Application

ApplicationsTask *--- ApplicationsManager
ApplicationsManager *-- MenuApplication
ApplicationsManager *-- "*" Application
ApplicationsManager *--- IoStateManager

@enduml
