@startuml

title L3 RTOS MESSAGES BETWEEN APPLICATIONS LAYER AND DOMAIN MODELS LAYER

skinparam packageStyle rectangle
skinparam lineThickness 2

'------------------------------------------------------------------------------------------------
'                           APPLICATIONS LAYER 
'------------------------------------------------------------------------------------------------

package "Applications Layer" #ff8
{
    class ApplicationsTask {}
} 

class LedStripsQueue <<queue>> 
{
    + Pixel(int horizontal, int vertical, RGB color)
    + Row(int row, RGB color)
    + Column(int column, RGB color)
    + Orientation(EOrientation orientation)
    + SyncToDriver()
}

class I2cOutputQueue <<queue>> 
{
}

struct OutputQueue_OutputMessage
{
    + enum class EType { Led, Lcd2004Line }
    + EType type
}

struct Types
{
    + enum class ELed Id { PlayPauseLed, SelectLed, SetupLed, Player1Led, Player2Led }
    + enum class EJoystickId { Player1, Player2 }
    + enum class EJoystickDirection { Centered, Up, UpRight, Right, DownRight, Down, DownLeft, Left, UpLeft }
}

struct led
{
    + ELedId ledId
    + bool state
}

struct lcd2004Line 
{
    + uint8_t lineNumber
    + char lineContent[Lcd2004::LINE_WIDTH]
}

OutputQueue_OutputMessage *-- led : union
OutputQueue_OutputMessage *-- lcd2004Line : union

I2cOutputQueue o-- OutputQueue_OutputMessage : type only

class I2cInputQueue <<queue>> 
{
}

ApplicationsTask --> LedStripsQueue
ApplicationsTask --> I2cOutputQueue
ApplicationsTask <-- I2cInputQueue

struct InputQueue_InputMessage
{
    + enum class EType { JoystickDirection, JoystickButton, SystemButton }
    + EType type
}

I2cInputQueue o-- InputQueue_InputMessage: type only

OutputQueue_OutputMessage ...> Types
InputQueue_InputMessage ...> Types

struct joystickDirection
{
    EJoystickId joystickId
    EJoystickDirection direction
}

struct joystickButton
{
    EJoystickId id
    bool pressed
} 

struct systemButton
{
    bool pressed
} 

InputQueue_InputMessage *-- joystickDirection
InputQueue_InputMessage *-- joystickButton
InputQueue_InputMessage *-- systemButton

package "Domain Models Layer" as DomainModelsLayer #fc8
{
    class I2cTask <<I2cTask>> #yellow
    class LedStripsTask <<LedStripTask>> #lightblue
}

LedStripsQueue --> LedStripsTask
I2cOutputQueue --> I2cTask
I2cInputQueue <-- I2cTask

@enduml
