@startuml

title L3 RTOS MESSAGES BETWEEN APPLICATIONS LAYER AND DOMAIN MODELS LAYER

skinparam packageStyle rectangle
skinparam lineThickness 2

'------------------------------------------------------------------------------------------------
'                           APPLICATIONS LAYER 
'------------------------------------------------------------------------------------------------

package "Applications Layer" #ff8
{
    class ApplicationsTask {}
} 

class LedStripsQueue <<queue>> 
{
    + Pixel(int horizontal, int vertical, RGB color)
    + Row(int row, RGB color)
    + Column(int column, RGB color)
    + Orientation(EOrientation orientation)
    + SyncToDriver()
}

class OutputQueue <<queue>> 
{
}

struct OutputMessage
{
    + enum class EType { Led, Lcd2004Line }
    + EType type
}

struct Types
{
    + enum class ELed Id { PlayPauseLed, SelectLed, SetupLed, Player1Led, Player2Led }
    + enum class EJoystickId { Player1, Player2 }
    + enum class EJoystickDirection { Centered, Up, UpRight, Right, DownRight, Down, DownLeft, Left, UpLeft }
}

struct led
{
    + ELedId ledId
    + bool state
}

struct lcd2004Line 
{
    + uint8_t lineNumber
    + char lineContent[Lcd2004::LINE_WIDTH]
}

OutputMessage *-- led : union
OutputMessage *-- lcd2004Line : union

OutputQueue o-- OutputMessage : type only

class InputQueue <<queue>> 
{
}

ApplicationsTask --> LedStripsQueue
ApplicationsTask --> OutputQueue
ApplicationsTask <-- InputQueue

struct InputMessage
{
    + enum class EType { JoystickDirection, JoystickButton, SystemButton }
    + EType type
}

InputQueue o-- InputMessage: type only

OutputMessage ...> Types
InputMessage ...> Types

struct joystickDirection
{
    EJoystickId joystickId
    EJoystickDirection direction
}

struct joystickButton
{
    EJoystickId id
    bool pressed
} 

struct systemButton
{
    bool pressed
} 

InputMessage *-- joystickDirection
InputMessage *-- joystickButton
InputMessage *-- systemButton

package "Domain Models Layer" as DomainModelsLayer #fc8
{
    class I2cTask <<I2cTask>> #yellow
    class LedStripsTask <<LedStripTask>> #lightblue
}

LedStripsQueue --> LedStripsTask
OutputQueue --> I2cTask
InputQueue <-- I2cTask

@enduml
