@startuml

title 4 DOMAIN MODELS LAYER

skinparam packageStyle rectangle
skinparam lineThickness 2

class I2cTask <<I2cTask>> #yellow
{
    + Initialize()
    + Run()
}

I2cTask *-- IoPins
ApplicationsTask ...> I2cTask : Initialize

class I2cTaskDelegateDeviceModels <<L5_DeviceModels>> #yellow
{
    Run()
}

I2cTask *- I2cTaskDelegateDeviceModels

interface IDomainModel 
{
}

class DomainModel 
{
}

DomainModel -u-|> IDomainModel

class IoPins <<I2cTask>> #yellow
{
    + GetI2cTask(): I2cTask
    + ELedId { PLAY, PAUSE, SETUP }
    + EJoystickId : { PLAYER_1, PLAYER_2 }
    + GetLed(ELedId ledId): Led
    + GetJoystick(EJoystickId joystickId): Joystick
    + GetSystemButton()
    + HandleMcp23017Interrupt()
}

IoPins -u-|> DomainModel

class Joystick  <<I2cTask>> #yellow
{
    - direction : EJoystickDirection
    - buttonState : bool
    + GetI2cTask() : I2cTask
    + GetDirection() : EJoystickDirection
    + GetButtonState(): bool
}

IoPins o-- "2" Joystick : (PLAYER_1, \n PLAYER_2)

class SystemButton <<I2cTask>> #yellow
{
    - state: bool 
    + GetState(): bool 
    + SetState(state: bool) 
}

SystemButton -u-|> DomainModel
IoPins o-- "1" SystemButton 

class Displays <<I2cTask>> #yellow
{
    + GetI2cTask() : I2cTask
    + ETm1637Id { CONTROL_PANEL, PLAYER_1, PLAYER_2 }
    + GetTm1637(ETm1637Id): Tm1637
    + GetLcd2004() : Lcd2004
}

Displays -u-|> DomainModel
I2cTask *-- Displays

class Led <<I2cTask>> #yellow
{
    - on: bool
    + GetLed(): bool
    + SetLed(bool on)
}

Led -u-|> DomainModel
IoPins o-- "3" Led : (PLAY, \n PAUSE, \n SETUP)

class Lcd2004 <<I2cTask>> #yellow
{
    - bool _screenEnabled
    - string _lines[4]
    - uint8_t _cursorX
    - uint8_t _cursorY
    - bool _cursorEnabled
    + EnableScreen(bool on)
    + WriteLine(int line, string text)
    + SetCursor(int x, int y)
    + EnableCursor(bool on)
}

Lcd2004 -u-|> DomainModel
Displays o-- Lcd2004

class Tm1637 <<I2cTask>> #yellow
{
    - EFormat { Value, Time, Text }
    - EFormat format
    - uint32_t firstValue { value / hours }
    - uint8_t secondValue  { minutes }
    - string _text
    + SetFormat(EFormat format)
    + SetTime(int first, int second) 
    + SetValue(int value)
    + SetText(string text)
}

Tm1637 -u-|> DomainModel
Displays o-- "3" Tm1637 : (CENTRAL_PANEL,\n PLAYER_1,\n PLAYER_2)

class LedStripsTask <<LedStripTask>> #lightblue
{
    + Initialize()
    + Run()
}

ApplicationsTask ..> LedStripsTask : Initialize

class LedStrips  <<LedStripTask>> #lightblue
{
    - pixels: RGB[5, 72] {stored as vertical}
    - orientation : EOrientation
    + Initialize()
    + SyncToDriver()
    + GetPixels(): RGB[uint16_t index]
    + SetPixel(uint8_t horizontal, uint8_t vertical, RGB color)
    + SetRow(uint8_t row, RGB color)
    + SetColumn(uint8_t column, RGB color)
}

LedStrips -u-|> DomainModel
LedStripsTask o- LedStrips

@enduml
