@startuml

title L4 DOMAIN MODELS LAYER

skinparam packageStyle rectangle
skinparam lineThickness 2

class I2cTask <<I2cTask, L0 Systems Layer>> #yellow
{
    + Initialize()
    + Run()
}

I2cTask *-- IoPins
ApplicationsTask ...> I2cTask : Initialize

class I2cTaskDelegateDeviceModels <<L5_DeviceModels>> #yellow
{
    Run()
}

I2cTask *- I2cTaskDelegateDeviceModels

interface IDomainModel 
{
}

class DomainModel 
{
    DomainModel()
}

DomainModel -u-|> IDomainModel

class IoPins <<I2cTask>> #yellow
{
    + IoPins()
    + SetDeviceModel(IDeviceModel& deviceModel)
    + GetDeviceModel() : Mcp23017DeviceModel&
    + GetLed(Types::ELedId ledId): Led
    + GetJoystick(Types::EJoystickId joystickId): Joystick
    + GetSystemButton()
    + UpdateInputs()
}

class Mcp23017DeviceModel <<L5 Device Models>>
IoPins o-- Mcp23017DeviceModel


IoPins -u-|> DomainModel

class Joystick  <<I2cTask>> #yellow
{
    + Joystick(IoPins& ioPins, Types::EJoystickId joystickId)
    + GetId() : Types::EJoystickId
    + GetDirection() : Types::EJoystickDirection
    + GetButtonState(): bool
    + GetButtonState() : bool
    + UpdateInputs()
    + GetButtonStateDirty() : Dirty 
    + GetDirectionDirty() : Dirty

private:
    - IoPins& _ioPins
    - Types::EJoystickId _id
    - bool _buttonState
    - Types::EJoystickDirection _direction
    - UpdateButtonState()
    - UpdateDirection()
}

class Dirty <<L9 Utilities>> {}

Joystick *-- "2" Dirty : _buttonStateDirty, \n_directionDirty

IoPins o-- "2" Joystick : (Player1, \nPlayer2)

class SystemButton <<I2cTask>> #yellow
{
    + SystemButton(IoPins& ioPins)
    + UpdateInput()
    + GetState(): bool 
    + GetStateDirty& Dirty&
    - IoPins& _ioPins;
    - bool _state
}

SystemButton *-- Dirty : _dirty

SystemButton -u-|> DomainModel
IoPins o-- "1" SystemButton 

class Displays <<I2cTask>> #yellow
{
    + Displays()
    + Lcd2004& GetLcd2004()
    + ETm1637Id& GetTm1637CentralPanel
    + ETm1637Id& GetTm1637Player1
    + ETm1637Id& GetTm1637CPlayer2
    + GetLcd2004() : Lcd2004
}

Displays -u-|> DomainModel
I2cTask *-- Displays

class Led <<I2cTask>> #yellow
{
    + Led(IoPins& ioPins, Types::ELedId ledId)
    - on: bool
    + GetState(): bool
    + SetState(bool state)
    - Types::ELedId _ledId
    - IoPins& _ioPins
}

Led -u-|> DomainModel
IoPins o-- "5" Led : (PlayPause,\nSelect,\nSetup,\nPlayer1,\nPlayer2)

class Lcd2004 <<I2cTask>> #yellow
{
    + Lcd2004()
    + <<static>> const uint8_t LINE_WIDTH = 20
    - bool _screenEnabled
    - string _lines[4]
    + SetDeviceModel(IDeviceModel& deviceModel)
    + SetLine(uint8_t lineNumber, string line)
}

class Lcd2004DeviceModel <<L5 Device Models>>
Lcd2004 o-- Lcd2004DeviceModel

Lcd2004 -u-|> DomainModel
Displays o-- Lcd2004

class Tm1637 <<I2cTask>> #yellow
{
    - EFormat { Value, Time, Text }
    - EFormat format
    - uint32_t firstValue { value / hours }
    - uint8_t secondValue  { minutes }
    - string _text
    + SetFormat(EFormat format)
    + SetTime(int first, int second) 
    + SetValue(int value)
    + SetText(string text)
}

Tm1637 -u-|> DomainModel
Displays o-- "3" Tm1637 : (CENTRAL_PANEL,\n PLAYER_1,\n PLAYER_2)

class DeviceModelsContext <<L1 Composition Layer>> {}

Displays o-- DeviceModelsContext
IoPins o-- DeviceModelsContext

class LedStripsTask <<LedStripTask>> #lightblue
{
    + Initialize()
    + Run()
}

class ApplicationsTask <<L2 Applications>>

ApplicationsTask ..> LedStripsTask : Initialize

class LedStrips  <<LedStripTask>> #lightblue
{
    - pixels: RGB[5, 72] {stored as vertical}
    - orientation : EOrientation
    + Initialize()
    + SyncToDriver()
    + GetPixels(): RGB[uint16_t index]
    + SetPixel(uint8_t horizontal, uint8_t vertical, RGB color)
    + SetRow(uint8_t row, RGB color)
    + SetColumn(uint8_t column, RGB color)
}

LedStrips -u-|> DomainModel
LedStripsTask o- LedStrips

class I2cOutputQueueReader #yellow
{
    + I2cOutputQueueReader(I2cOutputQueue& i2cOutputQueue, IoPins& ioPins, Displays& displays)
    + HandleMessage() : bool
}

I2cOutputQueueReader o-- IoPins
I2cOutputQueueReader o-- Displays

class I2cOutputQueue <<L3_Messages>> #yellow

I2cOutputQueueReader o-- I2cOutputQueue

class I2cInputQueueWriter #yellow
{
    + I2cInputQueueWriter(I2cInputQueue& i2cInputQueue, IoPins& ioPins);
    + SendMessages()
    - SendJoystickMessages(Joystick& joystick)
    - SendSystemButtonMessage(SystemButton& systemButton)
}

class I2cInputQueue <<L3 Messages>> #yellow

I2cInputQueueWriter o-- I2cInputQueue
I2cINputQueueWriter o-- IoPins

@enduml
