@startuml

title L6 DEVICE DRIVERS LAYER

skinparam packageStyle rectangle
skinparam lineThickness 2

class IDomainModel <<L4 Domain Model>> {}

interface IDeviceDriver
{
    + <abstract> Initialize() 
    + SetDomainModel(IDomainModel& domainModel)
    + GetDomainModel() : IDomainModel
}

class DeviceDriver
{
}

DeviceDriver o- IDomainModel
DeviceDriver -u-|> IDeviceDriver

package "Ws28xx DeviceDriver"
{
    abstract class Ws28xxDeviceDriver <<LedStripTask>> #lightblue
    {
        - pixelBufferForRmt : uint8_t[]
        + Initialize(uint8_t dataPin)
        + GetWs28xxModel : Ws28xxModel
        + SyncWithHardware()
    }

    Ws28xxDeviceDriver -u---|> DeviceDriver

    class EspWs28xxDeviceDriver <<LedStripTask>> #lightblue

    class WindowsWs28xxDeviceDriver <<LedStripTask>> #lightblue
    {
        -Timer60fps()
    }

    Ws28xxDeviceDriver <|-- EspWs28xxDeviceDriver
    Ws28xxDeviceDriver <|-- WindowsWs28xxDeviceDriver
}

package "I2C DeviceDriver"
{
    abstract class I2cDeviceDriver <<I2cTask>> #yellow
    {
        + <<abstract>> SetConfiguration(
            uint8_t i2cPort, uint8_t sdaPin, uint8_t sclPin, uint32_t i2cFrequency)
        + <<abstract>> Read(
            uint8_t deviceAddress, uint8_t* data, size_t length) 
        + <<abstract>> Write(
            uint8_t deviceAddress, const uint8_t* data, size_t length)
        + <<abstract>> ReadRegister(
            uint8_t deviceAddress, uint8_t registerAddress, uint8_t* data, size_t length)
        + <<abstract>> WriteRegister(
            uint8_t deviceAddress, uint8_t registerAddress, const uint8_t* data, size_t length)
    }

    I2cDeviceDriver -u-|> DeviceDriver

    class EspI2cDeviceDriver <<I2cTask>> #yellow
    {
        - i2c_port_t _i2cPort
        - gpio_num_t _sdaPin
        - gpio_num_t _sclPin
        - uint32_t _i2cFrequency
        + SetConfiguration(
            uint8_t i2cPort, uint8_t sdaPin, uint8_t sclPin, uint32_t i2cFrequency)
        + Read(
            uint8_t deviceAddress, uint8_t* data, size_t length) 
        + Write(
            uint8_t deviceAddress, const uint8_t* data, size_t length)
        + ReadRegister(
            uint8_t deviceAddress, uint8_t registerAddress, uint8_t* data, size_t length)
        + WriteRegister(
            uint8_t deviceAddress, uint8_t registerAddress, const uint8_t* data, size_t length)

    }

    class WindowsI2cDeviceDriver  <<I2cTask>> #yellow
    {
        - TimerXxxFps()
        + Read()
        + Write()
    }

    I2cDeviceDriver <|-- EspI2cDeviceDriver
    I2cDeviceDriver <|-- WindowsI2cDeviceDriver 
}

package "MCP23017 DeviceDriver"
{
    abstract class Mcp23017DeviceDriver <<I2cTask>> #yellow
    {
        - interrupt_triggered : bool
        - SendMcp23017Interrupt ()
        + <abstract> Initialize()
        + GetMcp23017Model() : Mcp23017Model
        + SyncWithHardware()
    }

    Mcp23017DeviceDriver -u-|> DeviceDriver

    class EspMcp23017DeviceDriver <<I2cTask>> #yellow
    {
        - InterruptABHandler
        + Initialize(uint8_t i2cAddress)
    }

    class WindowsMcp23017DeviceDriver <<I2cTask>> #yellow
    {
        - TimerXxxFps()
    }

    Mcp23017DeviceDriver <|-- EspMcp23017DeviceDriver
    Mcp23017DeviceDriver <|-- WindowsMcp23017DeviceDriver
    Mcp23017DeviceDriver *--- I2cDeviceDriver
}

package "2004 LCD DeviceDriver"
{
    abstract class Lcd2004DeviceDriver <<I2cTask>> #yellow
    {
        + Initialize(uint8_t i2cAddress)
        + GetLcd2004Model : Lcd2004Model
        + SyncWithHardware()


        + SetI2cDeviceDriver(I2cDeviceDriver& i2cDeviceDriver)
        + SendToDisplay()
        # <<abstract>> PrintChar(char c) 
        # <<abstract>> PrintLine(std::string line)
        # <<abstract>> SetCursor(uint8_t row, uint8_t column)

        - SendDifferentCharacters(uint8_t lineIndex)
        - SendFullLine(uint8_t lineIndex)
    }

    Lcd2004DeviceDriver -u-|> DeviceDriver

    class EspLcd2004DeviceDriver  <<I2cTask>> #yellow
    {
        + Initialize() 
        # PrintChar(char c)
        # PrintLine(std::string line)
        # SetCursor(uint8_t row, uint8_t column)
        - Command(uint8_t cmd)
	    - Data(uint8_t d)
    	- WriteNibble(uint8_t nibble, uint8_t rs)
	    - WriteByte(uint8_t byte, uint8_t rs)
    }

    class WindowsLcd2004DeviceDriver  <<I2cTask>> #yellow
    {
    }

    Lcd2004DeviceDriver <|-- EspLcd2004DeviceDriver
    Lcd2004DeviceDriver <|-- WindowsLcd2004DeviceDriver
    Lcd2004DeviceDriver  *--- I2cDeviceDriver
}

package "TM1637 DeviceDriver"
{
    abstract class Tm1637DeviceDriver <<I2cTask>> #yellow
    {
        + Initialize(uint8_t clkPin, uint8_t dataPin)
        + GetTm1637Model : Tm1637Model
        + SyncWithHardware()
    }

    Tm1637DeviceDriver -u-|> DeviceDriver

    class EspTm1637DeviceDriver  <<I2cTask>> #yellow
    {
    }

    class WindowsTm1637DeviceDriver  <<I2cTask>> #yellow
    {
    }

    Tm1637DeviceDriver <|-- EspTm1637DeviceDriver
    Tm1637DeviceDriver <|-- WindowsTm1637DeviceDriver
}

@enduml
