@startuml

participant M60_I2cTaskDeviceDriversDelegate
participant M60_Lcd2004DeviceDriver
participant M50_Lcd2004DeviceModel
participant M60_I2cDeviceDriver
participant M80_I2c
participant M70_GdiSimulator
participant M70_GdiScreen
participant M70_GdiLcd2004

M60_I2cTaskDeviceDriversDelegate --> M60_Lcd2004DeviceDriver : SendToDisplay()
M60_Lcd2004DeviceDriver --> M50_Lcd2004DeviceModel : IsCursorDirty
alt Cursor is dirty
   note right M60_Lcd2004DeviceDriver
       Todo
   end note
end
M60_Lcd2004DeviceDriver --> M50_Lcd2004DeviceModel : GetDirtyLineNumber
alt dirtyLineIndex != -1
    M60_Lcd2004DeviceDriver --> M50_Lcd2004DeviceModel : PerCharacterStrategy(\n dirtyLineIndex)
    alt PerCharacter
        M60_Lcd2004DeviceDriver --> M50_Lcd2004DeviceModel : SendDifferentCharacters(\n dirtyLineIndex)
        loop for each character
            M60_Lcd2004DeviceDriver --> M50_Lcd2004DeviceModel : PrintChar(char)
            M50_Lcd2004DeviceModel --> M60_I2cDeviceDriver : Write(i2cAddress,\n buf, sizeof(buf))
            M60_I2cDeviceDriver --> M80_I2c: MasterWriteToDevice(\n port, i2cAddress, \n data, length, timeout)
            M80_I2c --> M70_GdiSimulator : PostWM(\n I2cWrite, \n i2cAddress) 
            M70_GdiSimulator --> M70_GdiScreen : UpdateI2c(\n address) 
            M70_GdiScreen --> M70_GdiLcd2004 : Update()
            M70_GdiLcd2004 --> M50_Lcd2004DeviceModel : GetLine

        end
    alt FullLine
        M60_Lcd2004DeviceDriver --> M50_Lcd2004DeviceModel : SendFullLine(dirtyLineIndex)
    end
    M60_Lcd2004DeviceDriver --> M50_Lcd2004DeviceModel : UpdateLine(dirtyLineIndex)
end



@enduml